import type { Product } from "./types";
import { SEED_PRODUCT_IMAGES } from "./product-images";

/**
 * ข้อมูลสำรองให้เว็บรันได้ก่อนที่จะต่อ Supabase จริง
 * ตรงกับ supabase/migrations/0003_seed.sql — ถ้าแก้ที่นั่น แก้ที่นี่ด้วย
 */
const C = (name: string, slug: string): Product["companies"] => ({
  id: slug,
  name,
  slug,
  country: "Japan",
  logo_url: null,
});

const img = (slug: string) =>
  SEED_PRODUCT_IMAGES[slug] ?? `/images/products/${slug}.jpg`;

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "m1",
    slug: "sony-a7c-ii",
    product_no: "SNY-A7C2",
    name: "Sony A7C II",
    product_type: "camera",
    company_id: "sony",
    announced_date: "2023-08-29",
    status: "in_production",
    msrp: 79900,
    market_price: 68000,
    thumbnail_url: img("sony-a7c-ii"),
    summary: "ฟูลเฟรมตัวเล็ก น้ำหนักเบา AF แม่นมาก เหมาะกับสายพกพาและวิดีโอ",
    best_for: ["travel", "portrait", "vlog"],
    highlight: ["Full Frame ในบอดี้เล็ก", "IBIS 7 stop", "AI AF ตรวจจับคน/สัตว์"],
    avg_rating: 4.6,
    review_count: 128,
    companies: C("Sony", "sony"),
    camera_specs: {
      product_id: "m1",
      body_type: "Compact",
      sensor_size: "Full Frame",
      sensor_type: "BSI-CMOS",
      megapixels: 33,
      max_resolution: "7008 x 4672",
      iso_min: 100,
      iso_max: 51200,
      shutter_min: "30s",
      shutter_max: "1/4000",
      fps_burst: 10,
      video_max: "4K 60p",
      ibis: true,
      weather_sealed: true,
      screen_type: 'จอพลิก 3.0" ทัชสกรีน',
      viewfinder: "OLED 2.36M dot",
      battery_shots: 530,
      weight_g: 514,
      dimensions_mm: "124 x 71 x 63",
    },
  },
  {
    id: "m2",
    slug: "sony-a6700",
    product_no: "SNY-A6700",
    name: "Sony A6700",
    product_type: "camera",
    company_id: "sony",
    announced_date: "2023-07-12",
    status: "in_production",
    msrp: 54900,
    market_price: 46000,
    thumbnail_url: img("sony-a6700"),
    summary: "APS-C เรือธง ตัวคุ้มสำหรับสายวิดีโอที่ยังอยากได้ภาพนิ่งดี ๆ",
    best_for: ["vlog", "sport", "travel"],
    highlight: ["APS-C 26MP", "4K 120p", "จับโฟกัสไว"],
    avg_rating: 4.5,
    review_count: 86,
    companies: C("Sony", "sony"),
    camera_specs: {
      product_id: "m2",
      body_type: "Compact",
      sensor_size: "APS-C",
      sensor_type: "BSI-CMOS",
      megapixels: 26,
      max_resolution: "6192 x 4128",
      iso_min: 100,
      iso_max: 32000,
      shutter_min: "30s",
      shutter_max: "1/4000",
      fps_burst: 11,
      video_max: "4K 120p",
      ibis: true,
      weather_sealed: true,
      screen_type: 'จอพลิก 3.0" ทัชสกรีน',
      viewfinder: "OLED 2.36M dot",
      battery_shots: 570,
      weight_g: 493,
      dimensions_mm: "122 x 69 x 75",
    },
  },
  {
    id: "m3",
    slug: "canon-eos-r6-ii",
    product_no: "CAN-R6M2",
    name: "Canon EOS R6 Mark II",
    product_type: "camera",
    company_id: "canon",
    announced_date: "2022-11-02",
    status: "in_production",
    msrp: 89900,
    market_price: 72000,
    thumbnail_url: img("canon-eos-r6-ii"),
    summary: "ตัวกลางฟูลเฟรมของ Canon ถ่ายต่อเนื่อง 40 fps เหมาะกับงานอีเวนต์และกีฬา",
    best_for: ["sport", "wedding", "portrait"],
    highlight: ["40 fps ไฟฟ้า", "Dual Pixel AF II", "บอดี้กันละอองน้ำ"],
    avg_rating: 4.7,
    review_count: 154,
    companies: C("Canon", "canon"),
    camera_specs: {
      product_id: "m3",
      body_type: "SLR-style",
      sensor_size: "Full Frame",
      sensor_type: "CMOS",
      megapixels: 24.2,
      max_resolution: "6000 x 4000",
      iso_min: 100,
      iso_max: 102400,
      shutter_min: "30s",
      shutter_max: "1/8000",
      fps_burst: 40,
      video_max: "4K 60p",
      ibis: true,
      weather_sealed: true,
      screen_type: 'จอพลิก 3.0" ทัชสกรีน',
      viewfinder: "OLED 3.69M dot",
      battery_shots: 580,
      weight_g: 670,
      dimensions_mm: "138 x 98 x 88",
    },
  },
  {
    id: "m4",
    slug: "canon-eos-r50",
    product_no: "CAN-R50",
    name: "Canon EOS R50",
    product_type: "camera",
    company_id: "canon",
    announced_date: "2023-02-08",
    status: "in_production",
    msrp: 26900,
    market_price: 21000,
    thumbnail_url: img("canon-eos-r50"),
    summary: "มิเรอร์เลสตัวเริ่มต้น เบามาก ใช้ง่าย เหมาะกับมือใหม่และคอนเทนต์",
    best_for: ["beginner", "vlog", "travel"],
    highlight: ["น้ำหนัก 375 กรัม", "โหมดออโต้ฉลาด", "ราคาเข้าถึงง่าย"],
    avg_rating: 4.3,
    review_count: 62,
    companies: C("Canon", "canon"),
    camera_specs: {
      product_id: "m4",
      body_type: "SLR-style",
      sensor_size: "APS-C",
      sensor_type: "CMOS",
      megapixels: 24.2,
      max_resolution: "6000 x 4000",
      iso_min: 100,
      iso_max: 32000,
      shutter_min: "30s",
      shutter_max: "1/4000",
      fps_burst: 15,
      video_max: "4K 30p",
      ibis: false,
      weather_sealed: false,
      screen_type: 'จอพลิก 3.0" ทัชสกรีน',
      viewfinder: "OLED 2.36M dot",
      battery_shots: 370,
      weight_g: 375,
      dimensions_mm: "116 x 86 x 69",
    },
  },
  {
    id: "m5",
    slug: "nikon-z6-iii",
    product_no: "NKN-Z6M3",
    name: "Nikon Z6 III",
    product_type: "camera",
    company_id: "nikon",
    announced_date: "2024-06-17",
    status: "in_production",
    msrp: 89900,
    market_price: 79000,
    thumbnail_url: img("nikon-z6-iii"),
    summary: "เซนเซอร์ partially stacked ตัวแรกของโลก จุดเด่นคือวิดีโอ RAW ในตัว",
    best_for: ["video", "sport", "night"],
    highlight: ["Partially stacked sensor", "N-RAW ในตัว", "EVF สว่าง 4000 nits"],
    avg_rating: 4.6,
    review_count: 47,
    companies: C("Nikon", "nikon"),
    camera_specs: {
      product_id: "m5",
      body_type: "SLR-style",
      sensor_size: "Full Frame",
      sensor_type: "Partially stacked CMOS",
      megapixels: 24.5,
      max_resolution: "6048 x 4032",
      iso_min: 100,
      iso_max: 64000,
      shutter_min: "900s",
      shutter_max: "1/8000",
      fps_burst: 20,
      video_max: "6K 60p RAW",
      ibis: true,
      weather_sealed: true,
      screen_type: 'จอพลิก 3.2" ทัชสกรีน',
      viewfinder: "OLED 5.76M dot",
      battery_shots: 390,
      weight_g: 760,
      dimensions_mm: "139 x 102 x 74",
    },
  },
  {
    id: "m6",
    slug: "fujifilm-x-t5",
    product_no: "FJI-XT5",
    name: "Fujifilm X-T5",
    product_type: "camera",
    company_id: "fujifilm",
    announced_date: "2022-11-02",
    status: "in_production",
    msrp: 62900,
    market_price: 52000,
    thumbnail_url: img("fujifilm-x-t5"),
    summary: "APS-C 40MP ดีไซน์ปุ่มหมุนคลาสสิก ฟิล์มซิมูเลชันเป็นจุดขาย",
    best_for: ["street", "portrait", "travel"],
    highlight: ["40MP APS-C", "Film Simulation 19 แบบ", "ปุ่มหมุนแมนนวล"],
    avg_rating: 4.7,
    review_count: 203,
    companies: C("Fujifilm", "fujifilm"),
    camera_specs: {
      product_id: "m6",
      body_type: "SLR-style",
      sensor_size: "APS-C",
      sensor_type: "BSI-CMOS",
      megapixels: 40.2,
      max_resolution: "7728 x 5152",
      iso_min: 125,
      iso_max: 12800,
      shutter_min: "900s",
      shutter_max: "1/8000",
      fps_burst: 15,
      video_max: "6.2K 30p",
      ibis: true,
      weather_sealed: true,
      screen_type: 'จอพับ 3 ทาง 3.0"',
      viewfinder: "OLED 3.69M dot",
      battery_shots: 580,
      weight_g: 557,
      dimensions_mm: "130 x 91 x 64",
    },
  },
  {
    id: "m7",
    slug: "fujifilm-x100vi",
    product_no: "FJI-X100VI",
    name: "Fujifilm X100VI",
    product_type: "camera",
    company_id: "fujifilm",
    announced_date: "2024-02-20",
    status: "in_production",
    msrp: 56900,
    market_price: 62000,
    thumbnail_url: img("fujifilm-x100vi"),
    summary:
      "คอมแพ็กต์เลนส์ฟิกซ์ 35mm ยอดฮิตสายสตรีท ของขาดตลาดจนราคามือสองแพงกว่าป้าย",
    best_for: ["street", "travel", "daily"],
    highlight: ["เลนส์ฟิกซ์ 23mm f/2", "IBIS ครั้งแรกในซีรีส์", "ไวไฟน์เดอร์ไฮบริด"],
    avg_rating: 4.8,
    review_count: 311,
    companies: C("Fujifilm", "fujifilm"),
    camera_specs: {
      product_id: "m7",
      body_type: "Large Sensor Compact",
      sensor_size: "APS-C",
      sensor_type: "BSI-CMOS",
      megapixels: 40.2,
      max_resolution: "7728 x 5152",
      iso_min: 125,
      iso_max: 12800,
      shutter_min: "900s",
      shutter_max: "1/4000",
      fps_burst: 11,
      video_max: "6.2K 30p",
      ibis: true,
      weather_sealed: false,
      screen_type: 'จอพลิก 3.0" ทัชสกรีน',
      viewfinder: "Hybrid OVF/EVF",
      battery_shots: 450,
      weight_g: 521,
      dimensions_mm: "128 x 74 x 55",
    },
  },
  {
    id: "m8",
    slug: "olympus-om-1",
    product_no: "OLY-OM1",
    name: "OM System OM-1",
    product_type: "camera",
    company_id: "olympus",
    announced_date: "2022-02-15",
    status: "in_production",
    msrp: 79900,
    market_price: 49000,
    thumbnail_url: img("olympus-om-1"),
    summary: "MFT บอดี้ทนสภาพอากาศระดับ IP53 เหมาะสายเดินป่า ถ่ายนก",
    best_for: ["wildlife", "landscape", "travel"],
    highlight: ["กันน้ำ IP53", "50 fps AF/AE ต่อเนื่อง", "Live ND ในตัว"],
    avg_rating: 4.5,
    review_count: 74,
    companies: C("Olympus", "olympus"),
    camera_specs: {
      product_id: "m8",
      body_type: "SLR-style",
      sensor_size: "Four Thirds",
      sensor_type: "Stacked BSI-CMOS",
      megapixels: 20.4,
      max_resolution: "5184 x 3888",
      iso_min: 80,
      iso_max: 102400,
      shutter_min: "60s",
      shutter_max: "1/8000",
      fps_burst: 50,
      video_max: "4K 60p",
      ibis: true,
      weather_sealed: true,
      screen_type: 'จอพลิก 3.0" ทัชสกรีน',
      viewfinder: "OLED 5.76M dot",
      battery_shots: 520,
      weight_g: 599,
      dimensions_mm: "135 x 92 x 73",
    },
  },
  {
    id: "m9",
    slug: "panasonic-g100",
    product_no: "PAN-G100",
    name: "Panasonic Lumix G100",
    product_type: "camera",
    company_id: "panasonic",
    announced_date: "2020-06-24",
    status: "discontinued",
    msrp: 22900,
    market_price: 12000,
    thumbnail_url: img("panasonic-g100"),
    summary: "กล้อง vlog ตัวเล็ก มีไมค์ OZO 3 ทิศทางในตัว เลิกผลิตแล้วแต่มือสองคุ้ม",
    best_for: ["vlog", "beginner"],
    highlight: ["ไมค์ OZO ในตัว", "จอพลิกได้", "เลิกผลิตแล้ว ราคามือสองถูก"],
    avg_rating: 4.0,
    review_count: 39,
    companies: C("Panasonic", "panasonic"),
    camera_specs: {
      product_id: "m9",
      body_type: "SLR-style",
      sensor_size: "Four Thirds",
      sensor_type: "CMOS",
      megapixels: 20.3,
      max_resolution: "5184 x 3888",
      iso_min: 200,
      iso_max: 25600,
      shutter_min: "60s",
      shutter_max: "1/4000",
      fps_burst: 10,
      video_max: "4K 30p",
      ibis: false,
      weather_sealed: false,
      screen_type: 'จอพลิก 3.0" ทัชสกรีน',
      viewfinder: "OLED 3.68M dot",
      battery_shots: 270,
      weight_g: 352,
      dimensions_mm: "116 x 83 x 54",
    },
  },
  {
    id: "m10",
    slug: "sony-fe-50mm-f18",
    product_no: "SNY-FE5018",
    name: "Sony FE 50mm F1.8",
    product_type: "lens",
    company_id: "sony",
    announced_date: "2016-03-29",
    status: "in_production",
    msrp: 8990,
    market_price: 6000,
    thumbnail_url: img("sony-fe-50mm-f18"),
    summary: "เลนส์ฟิกซ์ราคาประหยัด ละลายหลังได้ดี เหมาะเป็นเลนส์ตัวที่สอง",
    best_for: ["portrait", "daily"],
    highlight: ["ราคาถูกที่สุดในกลุ่มฟิกซ์ FE", "เบา 186 กรัม"],
    avg_rating: 4.2,
    review_count: 91,
    companies: C("Sony", "sony"),
    lens_specs: {
      product_id: "m10",
      focal_min_mm: 50,
      focal_max_mm: 50,
      aperture_max: 1.8,
      aperture_min: 22,
      mount: "Sony E",
      is_prime: true,
      stabilization: false,
      filter_thread_mm: 49,
      min_focus_cm: 45,
      weight_g: 186,
    },
  },
  {
    id: "m11",
    slug: "sigma-18-50-f28",
    product_no: "SGM-1850DC",
    name: "Sigma 18-50mm F2.8 DC DN",
    product_type: "lens",
    company_id: "sigma",
    announced_date: "2021-10-06",
    status: "in_production",
    msrp: 19900,
    market_price: 15500,
    thumbnail_url: img("sigma-18-50-f28"),
    summary: "ซูมรูรับแสงคงที่ f/2.8 สำหรับ APS-C เล็กและเบาผิดปกติ",
    best_for: ["travel", "wedding", "daily"],
    highlight: ["f/2.8 ตลอดช่วง", "เล็กกว่าคู่แข่งครึ่งหนึ่ง"],
    avg_rating: 4.7,
    review_count: 143,
    companies: C("Sigma", "sigma"),
    lens_specs: {
      product_id: "m11",
      focal_min_mm: 18,
      focal_max_mm: 50,
      aperture_max: 2.8,
      aperture_min: 22,
      mount: "Sony E / Fuji X",
      is_prime: false,
      stabilization: false,
      filter_thread_mm: 55,
      min_focus_cm: 12.1,
      weight_g: 290,
    },
  },
  {
    id: "m12",
    slug: "canon-rf-50mm-f18",
    product_no: "CAN-RF5018",
    name: "Canon RF 50mm F1.8 STM",
    product_type: "lens",
    company_id: "canon",
    announced_date: "2020-11-04",
    status: "in_production",
    msrp: 7490,
    market_price: 5200,
    thumbnail_url: img("canon-rf-50mm-f18"),
    summary: "นิฟตี้ฟิฟตี้ของระบบ RF คุ้มที่สุดสำหรับมือใหม่",
    best_for: ["portrait", "beginner"],
    highlight: ["ราคาเบา", "STM เงียบ เหมาะถ่ายวิดีโอ"],
    avg_rating: 4.4,
    review_count: 118,
    companies: C("Canon", "canon"),
    lens_specs: {
      product_id: "m12",
      focal_min_mm: 50,
      focal_max_mm: 50,
      aperture_max: 1.8,
      aperture_min: 22,
      mount: "Canon RF",
      is_prime: true,
      stabilization: false,
      filter_thread_mm: 43,
      min_focus_cm: 30,
      weight_g: 160,
    },
  },
  {
    id: "m13",
    slug: "manfrotto-befree-3",
    product_no: "MNF-BF3",
    name: "Manfrotto Befree Advanced",
    product_type: "tripod",
    company_id: "manfrotto",
    announced_date: "2018-09-01",
    status: "in_production",
    msrp: 9900,
    market_price: 6500,
    thumbnail_url: img("manfrotto-befree-3"),
    summary: "ขาตั้งพับพกพา อลูมิเนียม พับสั้น 40 ซม. ใส่กระเป๋าเป้ได้",
    best_for: ["travel", "landscape"],
    highlight: ["พับสั้น 40 ซม.", "รับน้ำหนัก 8 กก."],
    avg_rating: 4.4,
    review_count: 55,
    companies: { id: "manfrotto", name: "Manfrotto", slug: "manfrotto", country: "Italy", logo_url: null },
  },
  {
    id: "m14",
    slug: "peak-design-slide",
    product_no: "PKD-SLIDE",
    name: "Peak Design Slide",
    product_type: "strap",
    company_id: "peak-design",
    announced_date: "2015-01-01",
    status: "in_production",
    msrp: 2790,
    market_price: 1900,
    thumbnail_url: img("peak-design-slide"),
    summary: "สายคล้องกล้องปรับความยาวไวด้วยมือเดียว ถอดเปลี่ยนได้",
    best_for: ["daily", "travel"],
    highlight: ["ปรับความยาวมือเดียว", "Anchor Link ถอดไว"],
    avg_rating: 4.6,
    review_count: 88,
    companies: { id: "peak-design", name: "Peak Design", slug: "peak-design", country: "USA", logo_url: null },
  },
];

export const MOCK_BRANDS = Array.from(
  new Map(MOCK_PRODUCTS.map((p) => [p.companies!.slug, p.companies!])).values()
);
